# SPDX-PackageName: ggbuild
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright Vercel, Inc. and the contributors.

"""Built-in Dockerfile templates for portable Linux targets."""

from __future__ import annotations

import dataclasses
import hashlib
import importlib.metadata
import importlib.resources
import os
import pathlib
import shlex

from ggbuild.tools.template import format_template

_GENERATED_HEADER = (
    "# Generated by `ggbuild ci render-workflow`; do not edit.\n"
)
_ACTION_GENERATED_HEADER = (
    "# Generated by `ggbuild ci render-action-context`; do not edit.\n"
)
_ACTION_ENTRYPOINT = "action-entrypoint.sh"
_ACTION_REGISTRY = "ghcr.io/vercel-labs/ggbuild"
_UV_IMAGE = "ghcr.io/astral-sh/uv:0.11.24"
_SCCACHE_VERSION = "0.17.0"
_SCCACHE_ARCHIVE_SHA256 = {
    "aarch64": (
        "821a86343191aa1cbab74bd42f9e93c9a63bf85e4742945f40d3ae84193c1c77"
    ),
    "x86_64": (
        "67c4a96dd237c1f518f6b36083f270f9976d516f1e57fce891755ea782e50006"
    ),
}
_SCCACHE_LICENSE_SHA256 = (
    "cfc7749b96f63bd31c3c42b5c471bf756814053e847c10f3eb003417bc523d30"
)
_BUSYBOX_IMAGE = (
    "alpine:3.16.2@sha256:"
    "65a2763f593ae85fab3b5406dc9e80f744ec5b449f269b699b5efd37a07ad32e"
)
_BUSYBOX_VERSION = "1.35.0"
_BUSYBOX_PACKAGE_VERSION = f"{_BUSYBOX_VERSION}-r18"
_BUSYBOX_SOURCE = (
    f"https://busybox.net/downloads/busybox-{_BUSYBOX_VERSION}.tar.bz2"
)
_BUSYBOX_SOURCE_SHA256 = (
    "faeeb244c35a348a334f4a59e44626ee870fb07b6884d68c10ae8bc19f83a694"
)
_BUSYBOX_BINARY_SHA256 = {
    "aarch64": (
        "0e10ececb31316b54ef90fa4053b3350b0c41658fc1b16b77f83512ba86ab746"
    ),
    "x86_64": (
        "b1806cb675bb31a1753059cd7afd39936ecd1ffae520c0622920b609a84142c2"
    ),
}
_MUSL_VERSION = "1.2.3"
_MUSL_SOURCE = f"https://musl.libc.org/releases/musl-{_MUSL_VERSION}.tar.gz"
_MUSL_SOURCE_SHA256 = (
    "7d5b0b6062521e4627e099e4c9dc8248d32a30285e959b7eecaa780cf8cfd4a4"
)
_LINUX_PLATFORMS = {
    "aarch64": "linux/arm64",
    "x86_64": "linux/amd64",
}
_LINUX_IMAGES = {
    "gnu": (
        "rockylinux:8@sha256:"
        "9794037624aaa6212aeada1d28861ef5e0a935adaf93e4ef79837119f2a2d04c"
    ),
    "musl": (
        "alpine:3.22.1@sha256:"
        "4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1"
    ),
}
_BARE_TEST_IMAGES = {
    "gnu": _LINUX_IMAGES["gnu"],
    "musl": _BUSYBOX_IMAGE,
}


def ggbuild_requirements() -> tuple[str, ...]:
    """Return ggbuild's declared runtime requirements."""
    requirements = importlib.metadata.requires("ggbuild")
    if not requirements:
        raise ValueError("installed ggbuild metadata has no requirements")
    return tuple(sorted(requirements))


def _format_requirements(requirements: tuple[str, ...]) -> str:
    return " \\\n".join(
        f"        {shlex.quote(requirement)}" for requirement in requirements
    )


def _local_python_setup() -> str:
    return (
        "RUN PYTHONDONTWRITEBYTECODE=1 UV_NO_CACHE=1 uv python install \\\n"
        "        --install-dir /opt/python 3.14 \\\n"
        "    && uv venv --python 3.14 /opt/venv \\\n"
        "    && PYTHONDONTWRITEBYTECODE=1 UV_NO_CACHE=1 uv pip install \\\n"
        "        --python /opt/venv/bin/python \\\n"
        f"{_format_requirements(ggbuild_requirements())}"
    )


_ACTION_PYTHON_SETUP = (
    "RUN PYTHONDONTWRITEBYTECODE=1 UV_NO_CACHE=1 uv python install \\\n"
    "        --install-dir /opt/python 3.14 \\\n"
    "    && uv venv --python 3.14 /opt/venv"
)


def action_entrypoint() -> str:
    """Return the packaged entrypoint used by registry-backed actions."""
    return (
        importlib.resources
        .files(__package__)
        .joinpath(_ACTION_ENTRYPOINT)
        .read_text(encoding="utf-8")
    )


def _digest_sources(sources: tuple[tuple[str, str], ...]) -> str:
    digest = hashlib.sha256()
    for name, source in sources:
        encoded = source.encode()
        digest.update(name.encode())
        digest.update(b"\0")
        digest.update(str(len(encoded)).encode())
        digest.update(b"\0")
        digest.update(encoded)
    return digest.hexdigest()


def _write_atomic(path: pathlib.Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    try:
        temporary.write_text(content, encoding="utf-8")
        temporary.replace(path)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


@dataclasses.dataclass(frozen=True, slots=True)
class DockerfileTemplate:
    """A packaged target Dockerfile template."""

    name: str
    resource: str

    def source(self) -> str:
        return (
            importlib.resources
            .files(__package__)
            .joinpath(self.resource)
            .read_text(encoding="utf-8")
        )

    @property
    def sha256(self) -> str:
        return hashlib.sha256(self.source().encode()).hexdigest()

    def render(
        self,
        *,
        base_image: str,
        variables: dict[str, str],
        python_setup: str | None = None,
        header: str = _GENERATED_HEADER,
    ) -> str:
        values = {
            **variables,
            "base_image": base_image,
            "python_setup": python_setup or _local_python_setup(),
        }
        try:
            rendered = format_template(self.source(), **values)
        except KeyError as error:
            raise ValueError(
                f"Docker template {self.name} requires variable {error}"
            ) from error
        return header + rendered


@dataclasses.dataclass(frozen=True, slots=True)
class LinuxDockerEnvironment:
    """ggbuild-owned container policy for one Linux target."""

    name: str
    target: str
    platform: str
    image: str
    template: DockerfileTemplate
    variables: tuple[tuple[str, str], ...]

    @property
    def template_variables(self) -> dict[str, str]:
        return {**dict(self.variables), "base_image": self.image}

    @property
    def template_sha256(self) -> str:
        return self.template.sha256

    @property
    def dockerfile_sha256(self) -> str:
        return hashlib.sha256(self.render_dockerfile().encode()).hexdigest()

    @property
    def action_source_sha256(self) -> str:
        return _digest_sources((
            ("Dockerfile", self.render_action_dockerfile()),
            (_ACTION_ENTRYPOINT, action_entrypoint()),
        ))

    @property
    def action_image(self) -> str:
        return f"{self.action_repository}:{self.action_tag}"

    @property
    def action_repository(self) -> str:
        return f"{_ACTION_REGISTRY}/{self.name}"

    @property
    def action_tag(self) -> str:
        return f"sha256-{self.action_source_sha256}"

    def render_dockerfile(self) -> str:
        return self.template.render(
            base_image=self.image,
            variables=dict(self.variables),
        )

    def render_action_dockerfile(self) -> str:
        rendered = self.template.render(
            base_image=self.image,
            variables=dict(self.variables),
            python_setup=_ACTION_PYTHON_SETUP,
            header=_ACTION_GENERATED_HEADER,
        )
        return (
            f"{rendered.rstrip()}\n\n"
            f"COPY --chmod=0755 {_ACTION_ENTRYPOINT} "
            "/usr/local/bin/ggbuild-action\n\n"
            "ENV GITHUB_WORKSPACE=/github/workspace\n"
            "ENV UV_CACHE_DIR=/github/workspace/.cache/uv\n"
            "WORKDIR /github/workspace\n"
            'ENTRYPOINT ["/usr/local/bin/ggbuild-action"]\n'
        )

    def write_action_context(
        self, destination: pathlib.Path
    ) -> tuple[pathlib.Path, ...]:
        dockerfile = destination / "Dockerfile"
        entrypoint = destination / _ACTION_ENTRYPOINT
        _write_atomic(dockerfile, self.render_action_dockerfile())
        _write_atomic(entrypoint, action_entrypoint())
        return dockerfile, entrypoint


_TEMPLATES = {
    "linux-gnu": DockerfileTemplate(
        name="linux-gnu", resource="Dockerfile.gnu.template"
    ),
    "linux-musl": DockerfileTemplate(
        name="linux-musl", resource="Dockerfile.musl.template"
    ),
    "test-linux-gnu": DockerfileTemplate(
        name="test-linux-gnu", resource="Dockerfile.test-gnu.template"
    ),
    "test-linux-musl": DockerfileTemplate(
        name="test-linux-musl", resource="Dockerfile.test-musl.template"
    ),
}


def dockerfile_template(name: str) -> DockerfileTemplate:
    try:
        return _TEMPLATES[name]
    except KeyError as error:
        supported = ", ".join(sorted(_TEMPLATES))
        raise ValueError(
            f"unknown Docker template {name!r}; expected one of: {supported}"
        ) from error


def docker_environment(target: str) -> LinuxDockerEnvironment:
    """Return the built-in container environment for a Linux target."""
    arch = target.partition("-")[0]
    variables: tuple[tuple[str, str], ...]
    try:
        platform = _LINUX_PLATFORMS[arch]
    except KeyError as error:
        raise ValueError(
            f"target {target} has no supported Docker architecture"
        ) from error

    if target.endswith("-unknown-linux-gnu"):
        libc = "gnu"
        variables = (
            ("glibc_baseline", "2.28"),
            ("uv_image", _UV_IMAGE),
            (
                "sccache_aarch64_sha256",
                _SCCACHE_ARCHIVE_SHA256["aarch64"],
            ),
            (
                "sccache_x86_64_sha256",
                _SCCACHE_ARCHIVE_SHA256["x86_64"],
            ),
            ("sccache_license_sha256", _SCCACHE_LICENSE_SHA256),
            ("sccache_version", _SCCACHE_VERSION),
        )
    elif target.endswith("-unknown-linux-musl"):
        libc = "musl"
        variables = (
            ("uv_image", _UV_IMAGE),
            (
                "sccache_aarch64_sha256",
                _SCCACHE_ARCHIVE_SHA256["aarch64"],
            ),
            (
                "sccache_x86_64_sha256",
                _SCCACHE_ARCHIVE_SHA256["x86_64"],
            ),
            ("sccache_license_sha256", _SCCACHE_LICENSE_SHA256),
            ("sccache_version", _SCCACHE_VERSION),
        )
    else:
        raise ValueError(f"target {target} has no built-in Docker environment")

    name = f"linux-{libc}"
    return LinuxDockerEnvironment(
        name=name,
        target=target,
        platform=platform,
        image=_LINUX_IMAGES[libc],
        template=dockerfile_template(name),
        variables=variables,
    )


def _bare_test_libc(target: str) -> str:
    if target in _BARE_TEST_IMAGES:
        return target
    if target.endswith("-unknown-linux-gnu"):
        return "gnu"
    if target.endswith("-unknown-linux-musl"):
        return "musl"
    raise ValueError(f"target {target} has no bare Linux test image")


def bare_test_dockerfile(target: str = "gnu") -> str:
    """Render a minimal ABI-floor runtime-test image."""
    libc = _bare_test_libc(target)
    return dockerfile_template(f"test-linux-{libc}").render(
        base_image=_BARE_TEST_IMAGES[libc],
        variables={
            "busybox_image": _BUSYBOX_IMAGE,
            "busybox_aarch64_sha256": _BUSYBOX_BINARY_SHA256["aarch64"],
            "busybox_source": _BUSYBOX_SOURCE,
            "busybox_source_sha256": _BUSYBOX_SOURCE_SHA256,
            "busybox_upstream_version": _BUSYBOX_VERSION,
            "busybox_version": _BUSYBOX_PACKAGE_VERSION,
            "busybox_x86_64_sha256": _BUSYBOX_BINARY_SHA256["x86_64"],
            "musl_source": _MUSL_SOURCE,
            "musl_source_sha256": _MUSL_SOURCE_SHA256,
            "musl_version": _MUSL_VERSION,
        },
    )


def bare_test_source_sha256(target: str = "gnu") -> str:
    return _digest_sources((("Dockerfile", bare_test_dockerfile(target)),))


def bare_test_repository(target: str = "gnu") -> str:
    return f"{_ACTION_REGISTRY}/test-linux-{_bare_test_libc(target)}"


def bare_test_tag(target: str = "gnu") -> str:
    return f"sha256-{bare_test_source_sha256(target)}"


def bare_test_image(target: str) -> str:
    """Return the pinned ABI-floor image used for Linux portability tests."""
    return f"{bare_test_repository(target)}:{bare_test_tag(target)}"


def write_bare_test_context(
    destination: pathlib.Path, target: str = "gnu"
) -> pathlib.Path:
    """Write a content-addressed minimal runtime-test image context."""
    dockerfile = destination / "Dockerfile"
    _write_atomic(dockerfile, bare_test_dockerfile(target))
    return dockerfile
