FROM @@uv_image AS uv

FROM scratch AS rootfs

FROM @@base_image AS builder

COPY --from=uv /uv /usr/local/bin/uv

RUN apk add --no-cache \
        autoconf \
        automake \
        bash \
        binutils \
        bison \
        build-base \
        bzip2 \
        cmake \
        coreutils \
        file \
        findutils \
        flex \
        gettext \
        git \
        libtool \
        linux-headers \
        mandoc-soelim \
        ninja \
        patch \
        patchelf \
        perl \
        pkgconf \
        tar \
        xz \
        zstd

RUN case "$(uname -m)" in \
        x86_64) sccache_arch=x86_64; sccache_sha256=@@sccache_x86_64_sha256 ;; \
        aarch64) sccache_arch=aarch64; sccache_sha256=@@sccache_aarch64_sha256 ;; \
        *) echo "unsupported sccache architecture: $(uname -m)" >&2; exit 1 ;; \
    esac \
    && wget -q \
        "https://github.com/mozilla/sccache/releases/download/v@@sccache_version/sccache-v@@sccache_version-${sccache_arch}-unknown-linux-musl.tar.gz" \
        -O /tmp/sccache.tar.gz \
    && echo "$sccache_sha256  /tmp/sccache.tar.gz" | sha256sum -c - \
    && tar -xzf /tmp/sccache.tar.gz -C /tmp \
    && install -m 0755 \
        "/tmp/sccache-v@@sccache_version-${sccache_arch}-unknown-linux-musl/sccache" \
        /usr/local/bin/sccache \
    && mkdir -p /usr/share/licenses/sccache \
    && wget -q \
        https://raw.githubusercontent.com/mozilla/sccache/v@@sccache_version/LICENSE \
        -O /usr/share/licenses/sccache/LICENSE \
    && echo '@@sccache_license_sha256  /usr/share/licenses/sccache/LICENSE' \
        | sha256sum -c - \
    && rm -rf /tmp/sccache*

ENV UV_PYTHON_INSTALL_DIR=/opt/python

@@python_setup

ENV PATH=/opt/venv/bin:/usr/local/bin:/usr/bin:/bin

FROM rootfs
COPY --from=builder / /

RUN rm -rf /etc/apk /lib/apk /usr/share/apk \
    && rm -f /sbin/apk

ENV PATH=/opt/venv/bin:/usr/local/bin:/usr/bin:/bin
